[build]
  command = "yarn build && mkdir -p ./.next/src/script && cp ./src/script/test.db ./.next/src/script/testdb.db && echo 'DB file copied to ./.next/src/script/testdb.db' && ls -l .next/src/script"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
