[build]
  command = "yarn build && mkdir -p $(pwd)/.next/src/script && cp $(pwd)/src/script/test.db $(pwd)/.next/src/script/testdb.db && echo 'DB file copied to $(pwd)/.next/src/script/testdb.db' && ls -l $(pwd)/.next/src/script"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
