[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[build.lifecycle.onBuild]]
  command = "mkdir -p .next/src/script && cp src/script/test.db .next/src/script/testdb.db"
