[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["src/script/testdb.db"]

[[build.lifecycle.onPostBuild]]
  command = "mkdir -p .next/src/script && cp src/script/testdb.db .next/src/script/testdb.db && echo 'DB file copied to .next/src/script/testdb.db' && ls -l .next/src/script"

