name: deploy

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: 175.45.194.207
          username: root
          password: rootgaza
          port: 22
          script: |
            whoami
            cd GazaFront
            pwd
            git pull origin dev
            source ~/.nvm/nvm.sh
            nvm -v
            nvm use 21
            yarn install
            pm2 kill
            pm2 start "yarn devbuild" --watch
            netstat -lntp
